#!/usr/bin/env bash

##################################################################
# deptUNIXUnmount - This script unmounts your Department UNIX account
# home directory in your local machine home directory at ~/deptUNIX.
##################################################################

function main () {
	# Description: Main control flow
	# Arguments:
	#   (none)
	# Return:
	#   (none)

	# Declare Required Variables
	extraOptArgStr=""
	fusermountPrefix=""
	# Handle command line arguments and options
	case ${#} in
		0 )
			;;
		* )
			for cmdLnArg in ${@} ; do
				case ${cmdLnArg} in
					-f )  # force: Force unmounting likely from incorrect argument to mounting script (deptUNIXMount)
						fusermountPrefix="sudo"
						;;
					* )
						echo "ERROR: Unknown command line option or argument" >2
						exit 1
						;;
				esac
			done
			;;
	esac
	if [ -d ${HOME}/deptUNIX ] ; then
		${fusermountPrefix} fusermount ${extraOptArgStr} -u ${HOME}/deptUNIX
		if [[ ${?} != 0 ]] ; then
			echo >2
			echo "ERROR: Unable to unmount; shutdown/sleep/hibernate at YOUR OWN RISK." >2
			echo >2
		fi
	fi
}

# Call main
main ${@}
